name: core
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  about:
    path: ../about
  search:
    path: ../search
  movies:
    path: ../movies
  tvseries:
    path: ../tvseries

  google_fonts: ^6.1.0
  equatable: ^2.0.5
  dartz: ^0.10.0
  sqflite: ^2.0.0+3
  cached_network_image: ^3.1.0
  http: ^1.1.0
  firebase_crashlytics: ^3.0.6
  firebase_analytics: ^10.6.0

  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  flutter_rating_bar: ^4.0.1
  get_it: ^7.6.4
  path_provider: ^2.1.1
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.8
  build_runner: ^2.0.4
  flutter_lints: ^2.0.0
  equatable: ^2.0.3
  bloc_test: ^9.1.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
